paths:
  data_root: "/home/bryan/mnt/cullen/Current Project Databases - NHP/2025 Cerebellum prosthesis"
  location: "Nike/NRR_RW003"
  session: "NRR_RW003"
  geom_mat_rel: "config/ImecPrimateStimRec128_BT_corrected_091525.mat"

# ---- preprocessing ----
highpass_hz: 300.0

probes:
  UA:
    n_channels: 256
    mapping_mat_rel: "config/1106-22, 24, 42, 44 SN 11386-024040.xlsm"
    camera_sync_ch: 134 # MAKE SURE THESE CHANNELS ARE CORRECT
    triangle_sync_ch: 138 # MAKE SURE THESE CHANNELS ARE CORRECT
    # geom_mat_rel: ""   # (optional) if you want a specific .mat for UA

  NN_DBS:
    local_radius_inner: 40 # Placeholder
    local_radius_outer: 120 # Placeholder
    n_channels: 32
    stim_channels: [1,2,3,4,5,6,7,8,9,10,11,12,21,22,23,24,25,26,27,28,29,30,31,32]
    rec_channels: [13,14,15,16,17,18,19,20]

  NPRW:
    local_radius_inner: 30
    local_radius_outer: 150
    n_channels: 128
    br_template_sync_ch: 0 # MAKE SURE THESE CHANNELS ARE CORRECT
    triangle_sync_ch: 1 # MAKE SURE THESE CHANNELS ARE CORRECT
    mapping_mat_rel: "config/ImecPrimateStimRec128_BT_corrected_091525.mat"
    neural_data_stream: "RHS2000 amplifier channel"
    stim_data_stream: "Stim channel"

# ---- chunking / parallel ----
parallel_jobs: 8
threads_per_worker: 1
chunk: "4s"

# ---- Intan firing rate (threshold MUA) ----
intan_rate_est:
  bin_ms: 10.0          # bin width for counts
  sigma_ms: 10.0       # Gaussian kernel std
  detect_threshold: 3
  peak_sign: "both"

# ---- BR firing rate (threshold MUA) ----
UA_rate_est:
  bin_ms: 20.0          # bin width for counts
  sigma_ms: 20.0       # Gaussian kernel std
  detect_threshold: 3
  peak_sign: "both"

# ---- per-session overrides ---- # Placeholder
default_stim_num: 1
sessions:
  BL_RW_003_Session_1:
    probe: "NPRW"

  Nike_reaching_002_Session_01:
    probe: "UA"
    array: "M1s" # Placeholder

  Bert_reaching_001:
    probe: "NPRW"
